### PR TITLE
NNP with some variant labbel -> move to clean for all variants

### PR DESCRIPTION
**Pull request by jaumeortola**
All NNP forms labelled with some variant are moved to src-clean.txt for all variants.

Does it make sense? @AzadehSafakish @evan-defran-lt

### CODE REVIEW

**Comment by jaumeortola** [comment]
Here you can see the list of transferred nouns better.
[NNP-moved-to-all.txt](https://github.com/languagetool-org/english-pos-dict/files/14238499/NNP-moved-to-all.txt)

Some of the last lines don't look like proper nouns, at least the units of measurement. 

```
dBW=NNP=gb,nz,za
exFAT=NNP=gb
kB=NNP=gb,nz,za
keV=NNP=gb
mA=NNP=gb
non-Chinese=NNP=gb
```

**Comment by evan-defran-lt** [comment]
> Some of the last lines don't look like proper nouns, at least the units of measurement.

> dBW=NNP=gb,nz,za
> exFAT=NNP=gb
> kB=NNP=gb,nz,za
> keV=NNP=gb
> mA=NNP=gb
> non-Chinese=NNP=gb

That's right. With the exception of `exFAT`, these are not proper nouns. Nor is `Yt`. I didn't review line-by-line, but didn't see anything out of the ordinary when spot checking. 

Do I understand correctly that in moving these to `src-clean`, they will be applicable to all variants?

**Comment by jaumeortola** [comment]
> That's right. With the exception of exFAT, these are not proper nouns. Nor is Yt. I didn't review line-by-line, but didn't see anything out of the ordinary when spot checking.

Thanks. We will discuss how to combine manual edits and scripting edits so that no information is lost. 

> Do I understand correctly that in moving these to src-clean, they will be applicable to all variants?

That is my proposal, yes. Any downside? Are there proper nouns that should be in some variants and not in others?

**Comment by evan-defran-lt** [comment]
> Any downside?

Not that I can see.

> Are there proper nouns that should be in some variants and not in others?

I can't think of any examples.

**Review by evan-defran-lt — APPROVED** [review]
LGTM

**Pull request merged**
